### ISSUE TITLE
Does Pinecone expose data in OpenTelemetry format?

### ISSUE THREAD

**Issue by pranay01** [pinecone-io/examples#168]
Found [here](https://www.pinecone.io/learn/rust-rewrite/) that Pinecone does have [opentelemetry](https://opentelemetry.io) APIs embedded. 

Is it also available publicly so that pinecone users can know where their request to pinecone is spending time in?

**Comment by jamescalam** [comment]
Hey @pranay01 — we don't expose them; we only expose some metrics in Prometheus format
