### ISSUE TITLE
Suggest example notebook update. Library moved.

### ISSUE THREAD

**Issue by bryanbarnard** [pinecone-io/examples#268]
https://github.com/pinecone-io/examples/blob/a7b13d0feec0f1080106679cf6a31449732f9ebc/learn/generation/langchain/handbook/06-langchain-agents.ipynb#L342C5-L343C59

Libraray 'langchain.chains.SQLDatabaseChain' appears to have moved to 'langchain_experimental.sql.SQLDatabaseChain'

I made the following changes to make it work:
```
# from langchain.chains import SQLDatabaseChain
from langchain_experimental.sql import SQLDatabaseChain
```

**Comment by DosticJelena** [comment]
Thank you for the note @bryanbarnard! 
This issue has been resolved with the following PR: https://github.com/pinecone-io/examples/pull/264.

**Comment by bryanbarnard** [comment]
Thanks @DosticJelena
