### ISSUE TITLE
Satellite image search notebook missing

### ISSUE THREAD

**Issue by estebanpdl** [pinecone-io/examples#274]
Hi there. I saw this notebook on Satellite image search a few months ago: https://github.com/pinecone-io/examples/blob/master/search/image/satellite-image-search/satellite-image-search.ipynb

It is not available anymore. Is the notebook somewhere? I tried to explore different branches, but I had no luck.
Is it possible to still have access to it?

Thank you,

**Comment by DosticJelena** [comment]
Hi @estebanpdl! I think you are looking for this example: https://github.com/pinecone-io/examples/blob/master/learn/search/image/satellite-image-search/satellite-image-search.ipynb
It has been moved to the /learn directory.
